### ISSUE TITLE
[建议] 希望可以明确一下依赖项目

### ISSUE THREAD

**Issue by CKylinMC** [FoskyM/wordpress-to-mxspace#1]
在运行的时候发现其实需要提前安装几个依赖项目。建议通过requirements.txt来记录。

依赖安装方式：
```
pip install -f requirements.txt
```

需要在项目放置的requirements.txt：
```
beautifulsoup4==4.12.3
dnspython==2.7.0
markdownify==0.13.1
phpserialize==1.3
pymongo==4.10.1
python-dateutil==2.9.0.post0
six==1.16.0
soupsieve==2.6
```

(可以通过`pip freeze > requirements.txt`来创建，建议在venv环境下记录依赖。)

*btw，我发现bson不是`pip install bson`的那个，而是`pymongo`的那个...*

**Comment by FoskyM** [comment]
感谢提醒，我给忘了。

**Comment by FoskyM** [comment]
已增加 `requirements.txt`。

_因为最开始验证数据格式的时候用了下 `pymongo` 的 `bson.decode_all` 方法，后面就没改了_
